import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { X } from "lucide-react";
import { Gift, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { getCachedJson } from "../utils/publicApi";

export default function OfferDisplay(){
 const {pathname}=useLocation(); const [offers,setOffers]=useState([]); const [closed,setClosed]=useState({});
 const barRef=useRef(null);
 useEffect(()=>{let active=true;const load=()=>getCachedJson("/api/offers",{force:true,maxAge:0}).then(d=>{if(active)setOffers(d.offers||[])}).catch(()=>{});load();const timer=window.setInterval(load,15000);window.addEventListener("focus",load);return()=>{active=false;window.clearInterval(timer);window.removeEventListener("focus",load)}},[]);
 const offer=useMemo(()=>offers.find(o=>(o.pages?.length?o.pages:["all"]).some(raw=>{const p=String(raw).trim().replace(/\/$/,"")||"/";const current=pathname.replace(/\/$/,"")||"/";return p==="all"||p==="*"||p===current||(p.endsWith("/*")&&current.startsWith(p.slice(0,-1)))})),[offers,pathname]);
 const isBar=offer?.displayType==="bar"&&!closed[offer?._id];
 useEffect(()=>{if(!isBar){document.documentElement.style.setProperty("--offer-bar-height","0px");return}const update=()=>document.documentElement.style.setProperty("--offer-bar-height",`${barRef.current?.offsetHeight||0}px`);update();const observer=new ResizeObserver(update);if(barRef.current)observer.observe(barRef.current);window.addEventListener("resize",update);return()=>{observer.disconnect();window.removeEventListener("resize",update);document.documentElement.style.setProperty("--offer-bar-height","0px")}},[isBar,offer?._id]);
 if(!offer||closed[offer._id])return null;
 const close=()=>{document.documentElement.style.setProperty("--offer-bar-height","0px");setClosed(c=>({...c,[offer._id]:true}))};
 const discount=offer.discountValue>0?(offer.discountType==="percentage"?`${offer.discountValue}% OFF`:`₹${offer.discountValue} OFF`):"";
 const claim=()=>{toast.success("Offer claimed successfully!",{description:offer.couponCode?`Coupon ${offer.couponCode} ready to use.`:"Our team will help you with this offer."});close()};
 const copy=()=>{navigator.clipboard?.writeText(offer.couponCode);toast.success("Coupon code copied")};
 const content=<><div className="flex min-w-0 items-center gap-3"><div className="hidden h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-white/15 shadow-inner sm:flex"><Gift size={22}/></div><div className="min-w-0 text-left"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1 rounded-full border border-white/25 bg-white/15 px-2.5 py-1 text-[10px] font-black uppercase tracking-wider"><Sparkles size={11}/>{offer.badge}</span>{discount&&<span className="rounded-full bg-amber-300 px-2.5 py-1 text-[11px] font-black text-slate-950">{discount}</span>}</div><strong className="mt-1 block text-base leading-tight sm:text-lg">{offer.title}</strong>{offer.description&&<span className="mt-0.5 block text-xs text-white/75 sm:text-sm">{offer.description}</span>}</div></div>{offer.couponCode&&<button onClick={copy} className="rounded-xl border border-dashed border-white/40 bg-black/15 px-3 py-2 text-xs font-bold tracking-wider transition hover:bg-white/15">{offer.couponCode}</button>}<Link onClick={claim} to={offer.buttonUrl||"/contact/"} className="shrink-0 rounded-xl bg-white px-5 py-2.5 text-sm font-black text-slate-950 shadow-lg transition hover:-translate-y-0.5 hover:shadow-xl">{offer.buttonLabel}</Link><button onClick={close} aria-label="Close offer" className="rounded-full p-1.5 text-white/70 transition hover:bg-white/15 hover:text-white"><X size={18}/></button></>;
 if(offer.displayType==="popup")return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/75 p-4 backdrop-blur-md"><div className="relative w-full max-w-xl overflow-hidden rounded-[var(--site-radius)] border border-white/20 p-[1px] shadow-[0_30px_100px_rgba(0,0,0,.6)]" style={{background:"linear-gradient(135deg,var(--site-primary),var(--site-accent))"}}><div className="flex flex-col items-center gap-6 rounded-[calc(var(--site-radius)-1px)] bg-[var(--site-surface)] p-8 text-center text-[var(--site-text)] sm:p-10">{content}{offer.terms&&<small className="text-[var(--site-muted)]">{offer.terms}</small>}</div></div></div>;
 const panel=<div ref={isBar?barRef:null} className={`${isBar?"fixed left-0 right-0 top-0 z-[90] border-b border-cyan-300/20":"relative z-20 mx-auto my-4 max-w-6xl rounded-2xl border border-cyan-300/20"} flex flex-wrap items-center justify-center gap-x-5 gap-y-3 overflow-hidden px-5 py-3.5 text-center text-sm text-white shadow-[0_12px_40px_rgba(0,0,0,.38)]`} style={{background:"linear-gradient(105deg,#050b14 0%,#092033 48%,#0c3441 100%)"}}><span className="pointer-events-none absolute -left-10 h-28 w-28 rounded-full bg-cyan-400/20 blur-2xl"/><span className="pointer-events-none absolute right-[12%] h-20 w-20 rounded-full bg-blue-500/15 blur-2xl"/>{content}</div>;
 return isBar?<>{panel}<div aria-hidden="true" style={{height:"var(--offer-bar-height, 0px)"}}/></>:panel;
}
