import {
  FaBullhorn,
  FaChartLine,
  FaCode,
  FaMapMarkerAlt,
  FaMobileAlt,
  FaPaintBrush,
  FaPalette,
  FaRocket,
  FaSearch,
  FaShareAlt,
  FaShoppingCart,
   FaGoogle,
FaServer,
FaGlobe,
FaEnvelope,
FaDatabase,
FaCloud,
FaFacebookF,
FaInstagram,
FaLinkedinIn,
FaYoutube,
// FaFigma,
// FaExpress,
FaBootstrap,
FaHtml5, FaCss3Alt,
} from "react-icons/fa";

const iconMap = {
  FaCode,
  FaShoppingCart,
  FaPaintBrush,
  FaSearch,
  FaMapMarkerAlt,
  FaBullhorn,
  FaShareAlt,
  FaServer,
  FaMobileAlt,
  FaRocket,
  FaChartLine,
  FaPalette,
  FaGoogle,
FaGlobe,
FaEnvelope,
FaDatabase,
FaCloud,
FaFacebookF,
FaInstagram,
FaLinkedinIn,
FaYoutube,
// FaFigma,
// FaExpress,
FaBootstrap,
FaHtml5, FaCss3Alt,
};

export { FaCode };
export default iconMap;




// import {
//   FaBullhorn,
//   FaChartLine,
//   FaCode,
//   FaMapMarkerAlt,
//   FaMobileAlt,
//   FaPaintBrush,
//   FaPalette,
//   FaRocket,
//   FaSearch,
//   FaServer,
//   FaShareAlt,
//   FaShoppingCart,
//   FaReact,
//   FaNodeJs,
//   FaWordpress,
//   FaFacebookF,
//   FaInstagram,
//   FaLinkedinIn,
//   FaYoutube,
//   // FaXTwitter,
//   FaAws,
//   FaGithub,
//   FaBootstrap,
//   FaHtml5,
//   FaCss3Alt,
//   FaLaravel,
//   FaCcStripe,
//   FaGoogle,
//   FaStar,
//   FaTools,
//   FaFigma,
// } from "react-icons/fa";

// import {
//   SiExpress,
//   SiMongodb,
//   SiNextdotjs,
//   SiShopify,
//   SiWoocommerce,
//   SiRazorpay,
//   SiGoogleads,
//   SiGooglesearchconsole,
//   SiGoogletagmanager,
//   SiGooglemaps,
//   SiMeta,
//   SiSemrush,
//   // SiAhrefs,
//   SiYoast,
//   // SiCanva,
//   SiBuffer,
//   SiHootsuite,
//   SiCloudflare,
//   // SiGoogleworkspace,
//   // SiMicrosoftoffice,
//   SiHostinger,
//   SiGodaddy,
//   SiNamecheap,
//   SiDigitalocean,
//   SiCpanel,
//   SiPlesk,
//   SiTailwindcss,
//   SiFramer,
//   SiMui,
//   // SiAdobephotoshop,
//   // SiAdobeillustrator,
//   // SiAdobexd,
// } from "react-icons/si";

// const iconMap = {
//   // Service Icons
//   FaCode,
//   FaShoppingCart,
//   FaPaintBrush,
//   FaSearch,
//   FaMapMarkerAlt,
//   FaBullhorn,
//   FaShareAlt,
//   FaServer,
//   FaMobileAlt,
//   FaRocket,
//   FaChartLine,
//   FaPalette,
//   FaTools,

//   // Technology Icons
//   FaReact,
//   FaNodeJs,
//   FaWordpress,
//   FaFacebookF,
//   FaInstagram,
//   FaLinkedinIn,
//   FaYoutube,
//   FaXTwitter,
//   FaAws,
//   FaGithub,
//   FaBootstrap,
//   FaHtml5,
//   FaCss3Alt,
//   FaLaravel,
//   FaCcStripe,
//   FaGoogle,
//   FaStar,
//   FaFigma,

//   SiExpress,
//   SiMongodb,
//   SiNextdotjs,
//   SiShopify,
//   SiWoocommerce,
//   SiRazorpay,
//   SiGoogleads,
//   SiGooglesearchconsole,
//   SiGoogletagmanager,
//   SiGooglemaps,
//   SiMeta,
//   SiSemrush,
//   SiAhrefs,
//   SiYoast,
//   SiCanva,
//   SiBuffer,
//   SiHootsuite,
//   SiCloudflare,
//   SiGoogleworkspace,
//   SiMicrosoftoffice,
//   SiHostinger,
//   SiGodaddy,
//   SiNamecheap,
//   SiDigitalocean,
//   SiCpanel,
//   SiPlesk,
//   SiTailwindcss,
//   SiFramer,
//   SiMui,
//   SiAdobephotoshop,
//   SiAdobeillustrator,
//   SiAdobexd,
// };

// export default iconMap;